<?php if(!defined('IN_PHPVMS') && IN_PHPVMS !== true) { die(); } ?>
[VA_CONFIG]
DOWNLOADURL = <?php echo actionurl('/fsfk/vaconfig_template'); ?>

DOWNLOADURL_LIVEACARS_TEMPLATE = <?php echo actionurl('/fsfk/liveacars_template'); ?>

DOWNLOADURL_PIREP_TEMPLATE = <?php echo actionurl('/fsfk/pirep_template'); ?>

DOWNLOADURL_EMAL_TEMPLATE = <?php echo actionurl('/fsfk/email_template'); ?>

DOWNLOADURL_AIRTV_TEMPLATE = <?php echo actionurl('/fsfk/airtv_template'); ?>


EVENT_LOG_MODE = FULLPLUS
FORCE_RECORDING_OF_ALL_EVENTS = FALSE

AUTOCONNECT_LIVEACARS = FALSE
DISABLE_DISCONNECT_LIVEACARS = FALSE
AUTO_WEB_PIREP = FALSE
AUTO_EMAIL_PIREP = FALSE
AUTO_FLIGHTCRITIQUE = TRUE

DISABLE_WORLD_MENU = FALSE
DISABLE_AIRCRAFT_MENU = FALSE
DISABLE_FLIGHTS_MENU = FALSE
DISABLE_OPTIONS_MENU = FALSE
DISABLE_ALL_MENUS = FALSE

DISABLE_PAUSE = FALSE
DISABLE_SLEW = TRUE

MAX_SIM_RATE = 2
FORCE_CRASH_DETECTION = FALSE